envOffset: [10, 2]
prob_ground: 0.5
surroundings:
  stepping_stones:
    texture: "none"
    static_friction: 1.0 # [-]
    dynamic_friction: 1.0 # [-]
    restitution: 0. # [-]
    surrounding_origin: [0.0, 0., 0.]
robot_origin: [[-0.8, 0., 0.35], [1.5, 0., 0.35]]
vision:
  get_image: True
  use_height_map: False
  image_type: "depth" # depth, rgb, rgbd
  frame_stack: 2
  update_freq: 4 # how many control steps do we update the image buffer
  width: 64
  height: 64
  camera_number: 2
  camera_angle: 0

groundType:
  name: "stepping_stones" # plane, mountain range,
  staticFriction: 10.0 # [-]
  dynamicFriction: 10.0 # [-]
  restitution: 0. # [-]

# viewer cam:
viewer:
  refEnv: 0
  pos: [5, -5, 4.0] # [m]
  lookat: [4, 0, 0.2] # [m]

